language: python
sudo: false

env:
  - LUA="lua 5.1"
  - LUA="lua 5.2"
  - LUA="lua 5.3"
  - LUA="luajit 2.0"
  - LUA="luajit 2.1"

before_install:
  - pip install hererocks
  - hererocks env -r^ --$LUA
  - export PATH=$PWD/env/bin:$PATH

install:
  - luarocks make rockspecs/luacov-scm-1.rockspec

script:
  - lua tests/cli.lua
  - lua tests/filefilter.lua
  - lua tests/linescanner.lua
